/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as TeaserPublicIdRouteImport } from './routes/teaser.$publicId'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScenariosRouteImport } from './routes/app.scenarios'
import { Route as AppRoadmapRouteImport } from './routes/app.roadmap'
import { Route as AppRecommendationsRouteImport } from './routes/app.recommendations'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppImproveValueRouteImport } from './routes/app.improve-value'
import { Route as AppHealthScoreRouteImport } from './routes/app.health-score'
import { Route as AppFinancialsRouteImport } from './routes/app.financials'
import { Route as AppDataRoomRouteImport } from './routes/app.data-room'
import { Route as AppBuyerTeaserRouteImport } from './routes/app.buyer-teaser'
import { Route as AppAdvisorsRouteImport } from './routes/app.advisors'
import { Route as ApiPublicXeroCallbackRouteImport } from './routes/api.public.xero.callback'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TeaserPublicIdRoute = TeaserPublicIdRouteImport.update({
  id: '/teaser/$publicId',
  path: '/teaser/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppImproveValueRoute = AppImproveValueRouteImport.update({
  id: '/improve-value',
  path: '/improve-value',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthScoreRoute = AppHealthScoreRouteImport.update({
  id: '/health-score',
  path: '/health-score',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialsRoute = AppFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoomRoute = AppDataRoomRouteImport.update({
  id: '/data-room',
  path: '/data-room',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerTeaserRoute = AppBuyerTeaserRouteImport.update({
  id: '/buyer-teaser',
  path: '/buyer-teaser',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorsRoute = AppAdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicXeroCallbackRoute = ApiPublicXeroCallbackRouteImport.update({
  id: '/api/public/xero/callback',
  path: '/api/public/xero/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/advisors': typeof AppAdvisorsRoute
  '/app/buyer-teaser': typeof AppBuyerTeaserRoute
  '/app/data-room': typeof AppDataRoomRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/health-score': typeof AppHealthScoreRoute
  '/app/improve-value': typeof AppImproveValueRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/settings': typeof AppSettingsRoute
  '/teaser/$publicId': typeof TeaserPublicIdRoute
  '/app/': typeof AppIndexRoute
  '/api/public/xero/callback': typeof ApiPublicXeroCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/advisors': typeof AppAdvisorsRoute
  '/app/buyer-teaser': typeof AppBuyerTeaserRoute
  '/app/data-room': typeof AppDataRoomRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/health-score': typeof AppHealthScoreRoute
  '/app/improve-value': typeof AppImproveValueRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/settings': typeof AppSettingsRoute
  '/teaser/$publicId': typeof TeaserPublicIdRoute
  '/app': typeof AppIndexRoute
  '/api/public/xero/callback': typeof ApiPublicXeroCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/advisors': typeof AppAdvisorsRoute
  '/app/buyer-teaser': typeof AppBuyerTeaserRoute
  '/app/data-room': typeof AppDataRoomRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/health-score': typeof AppHealthScoreRoute
  '/app/improve-value': typeof AppImproveValueRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/settings': typeof AppSettingsRoute
  '/teaser/$publicId': typeof TeaserPublicIdRoute
  '/app/': typeof AppIndexRoute
  '/api/public/xero/callback': typeof ApiPublicXeroCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/demo'
    | '/reset-password'
    | '/app/advisors'
    | '/app/buyer-teaser'
    | '/app/data-room'
    | '/app/financials'
    | '/app/health-score'
    | '/app/improve-value'
    | '/app/onboarding'
    | '/app/recommendations'
    | '/app/roadmap'
    | '/app/scenarios'
    | '/app/settings'
    | '/teaser/$publicId'
    | '/app/'
    | '/api/public/xero/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/reset-password'
    | '/app/advisors'
    | '/app/buyer-teaser'
    | '/app/data-room'
    | '/app/financials'
    | '/app/health-score'
    | '/app/improve-value'
    | '/app/onboarding'
    | '/app/recommendations'
    | '/app/roadmap'
    | '/app/scenarios'
    | '/app/settings'
    | '/teaser/$publicId'
    | '/app'
    | '/api/public/xero/callback'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/demo'
    | '/reset-password'
    | '/app/advisors'
    | '/app/buyer-teaser'
    | '/app/data-room'
    | '/app/financials'
    | '/app/health-score'
    | '/app/improve-value'
    | '/app/onboarding'
    | '/app/recommendations'
    | '/app/roadmap'
    | '/app/scenarios'
    | '/app/settings'
    | '/teaser/$publicId'
    | '/app/'
    | '/api/public/xero/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TeaserPublicIdRoute: typeof TeaserPublicIdRoute
  ApiPublicXeroCallbackRoute: typeof ApiPublicXeroCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/teaser/$publicId': {
      id: '/teaser/$publicId'
      path: '/teaser/$publicId'
      fullPath: '/teaser/$publicId'
      preLoaderRoute: typeof TeaserPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios': {
      id: '/app/scenarios'
      path: '/scenarios'
      fullPath: '/app/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roadmap': {
      id: '/app/roadmap'
      path: '/roadmap'
      fullPath: '/app/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recommendations': {
      id: '/app/recommendations'
      path: '/recommendations'
      fullPath: '/app/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/improve-value': {
      id: '/app/improve-value'
      path: '/improve-value'
      fullPath: '/app/improve-value'
      preLoaderRoute: typeof AppImproveValueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health-score': {
      id: '/app/health-score'
      path: '/health-score'
      fullPath: '/app/health-score'
      preLoaderRoute: typeof AppHealthScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financials': {
      id: '/app/financials'
      path: '/financials'
      fullPath: '/app/financials'
      preLoaderRoute: typeof AppFinancialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data-room': {
      id: '/app/data-room'
      path: '/data-room'
      fullPath: '/app/data-room'
      preLoaderRoute: typeof AppDataRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyer-teaser': {
      id: '/app/buyer-teaser'
      path: '/buyer-teaser'
      fullPath: '/app/buyer-teaser'
      preLoaderRoute: typeof AppBuyerTeaserRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advisors': {
      id: '/app/advisors'
      path: '/advisors'
      fullPath: '/app/advisors'
      preLoaderRoute: typeof AppAdvisorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/xero/callback': {
      id: '/api/public/xero/callback'
      path: '/api/public/xero/callback'
      fullPath: '/api/public/xero/callback'
      preLoaderRoute: typeof ApiPublicXeroCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdvisorsRoute: typeof AppAdvisorsRoute
  AppBuyerTeaserRoute: typeof AppBuyerTeaserRoute
  AppDataRoomRoute: typeof AppDataRoomRoute
  AppFinancialsRoute: typeof AppFinancialsRoute
  AppHealthScoreRoute: typeof AppHealthScoreRoute
  AppImproveValueRoute: typeof AppImproveValueRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppScenariosRoute: typeof AppScenariosRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisorsRoute: AppAdvisorsRoute,
  AppBuyerTeaserRoute: AppBuyerTeaserRoute,
  AppDataRoomRoute: AppDataRoomRoute,
  AppFinancialsRoute: AppFinancialsRoute,
  AppHealthScoreRoute: AppHealthScoreRoute,
  AppImproveValueRoute: AppImproveValueRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppScenariosRoute: AppScenariosRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TeaserPublicIdRoute: TeaserPublicIdRoute,
  ApiPublicXeroCallbackRoute: ApiPublicXeroCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
