/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as TeaserPublicIdRouteImport } from './routes/teaser.$publicId'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScenariosRouteImport } from './routes/app.scenarios'
import { Route as AppRoadmapRouteImport } from './routes/app.roadmap'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRecommendationsRouteImport } from './routes/app.recommendations'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppImproveValueRouteImport } from './routes/app.improve-value'
import { Route as AppHealthScoreRouteImport } from './routes/app.health-score'
import { Route as AppFinancialsRouteImport } from './routes/app.financials'
import { Route as AppDataRoomRouteImport } from './routes/app.data-room'
import { Route as AppBuyerTeaserRouteImport } from './routes/app.buyer-teaser'
import { Route as AppBuyerRequestsRouteImport } from './routes/app.buyer-requests'
import { Route as AppAdvisorsRouteImport } from './routes/app.advisors'
import { Route as AdvisorDeclineInviteIdRouteImport } from './routes/advisor.decline.$inviteId'
import { Route as AdvisorAcceptInviteIdRouteImport } from './routes/advisor.accept.$inviteId'
import { Route as ApiPublicXeroCallbackRouteImport } from './routes/api.public.xero.callback'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api.public.stripe.webhook'
import { Route as ApiPublicQuickbooksCallbackRouteImport } from './routes/api.public.quickbooks.callback'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TeaserPublicIdRoute = TeaserPublicIdRouteImport.update({
  id: '/teaser/$publicId',
  path: '/teaser/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppImproveValueRoute = AppImproveValueRouteImport.update({
  id: '/improve-value',
  path: '/improve-value',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthScoreRoute = AppHealthScoreRouteImport.update({
  id: '/health-score',
  path: '/health-score',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialsRoute = AppFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoomRoute = AppDataRoomRouteImport.update({
  id: '/data-room',
  path: '/data-room',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerTeaserRoute = AppBuyerTeaserRouteImport.update({
  id: '/buyer-teaser',
  path: '/buyer-teaser',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerRequestsRoute = AppBuyerRequestsRouteImport.update({
  id: '/buyer-requests',
  path: '/buyer-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorsRoute = AppAdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => AppRoute,
} as any)
const AdvisorDeclineInviteIdRoute = AdvisorDeclineInviteIdRouteImport.update({
  id: '/decline/$inviteId',
  path: '/decline/$inviteId',
  getParentRoute: () => AdvisorRoute,
} as any)
const AdvisorAcceptInviteIdRoute = AdvisorAcceptInviteIdRouteImport.update({
  id: '/accept/$inviteId',
  path: '/accept/$inviteId',
  getParentRoute: () => AdvisorRoute,
} as any)
const ApiPublicXeroCallbackRoute = ApiPublicXeroCallbackRouteImport.update({
  id: '/api/public/xero/callback',
  path: '/api/public/xero/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuickbooksCallbackRoute =
  ApiPublicQuickbooksCallbackRouteImport.update({
    id: '/api/public/quickbooks/callback',
    path: '/api/public/quickbooks/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/advisors': typeof AppAdvisorsRoute
  '/app/buyer-requests': typeof AppBuyerRequestsRoute
  '/app/buyer-teaser': typeof AppBuyerTeaserRoute
  '/app/data-room': typeof AppDataRoomRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/health-score': typeof AppHealthScoreRoute
  '/app/improve-value': typeof AppImproveValueRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/settings': typeof AppSettingsRoute
  '/teaser/$publicId': typeof TeaserPublicIdRoute
  '/app/': typeof AppIndexRoute
  '/advisor/accept/$inviteId': typeof AdvisorAcceptInviteIdRoute
  '/advisor/decline/$inviteId': typeof AdvisorDeclineInviteIdRoute
  '/api/public/quickbooks/callback': typeof ApiPublicQuickbooksCallbackRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/xero/callback': typeof ApiPublicXeroCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/advisors': typeof AppAdvisorsRoute
  '/app/buyer-requests': typeof AppBuyerRequestsRoute
  '/app/buyer-teaser': typeof AppBuyerTeaserRoute
  '/app/data-room': typeof AppDataRoomRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/health-score': typeof AppHealthScoreRoute
  '/app/improve-value': typeof AppImproveValueRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/settings': typeof AppSettingsRoute
  '/teaser/$publicId': typeof TeaserPublicIdRoute
  '/app': typeof AppIndexRoute
  '/advisor/accept/$inviteId': typeof AdvisorAcceptInviteIdRoute
  '/advisor/decline/$inviteId': typeof AdvisorDeclineInviteIdRoute
  '/api/public/quickbooks/callback': typeof ApiPublicQuickbooksCallbackRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/xero/callback': typeof ApiPublicXeroCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/advisors': typeof AppAdvisorsRoute
  '/app/buyer-requests': typeof AppBuyerRequestsRoute
  '/app/buyer-teaser': typeof AppBuyerTeaserRoute
  '/app/data-room': typeof AppDataRoomRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/health-score': typeof AppHealthScoreRoute
  '/app/improve-value': typeof AppImproveValueRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/settings': typeof AppSettingsRoute
  '/teaser/$publicId': typeof TeaserPublicIdRoute
  '/app/': typeof AppIndexRoute
  '/advisor/accept/$inviteId': typeof AdvisorAcceptInviteIdRoute
  '/advisor/decline/$inviteId': typeof AdvisorDeclineInviteIdRoute
  '/api/public/quickbooks/callback': typeof ApiPublicQuickbooksCallbackRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/xero/callback': typeof ApiPublicXeroCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/app'
    | '/auth'
    | '/demo'
    | '/methodology'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/terms'
    | '/unsubscribe'
    | '/app/advisors'
    | '/app/buyer-requests'
    | '/app/buyer-teaser'
    | '/app/data-room'
    | '/app/financials'
    | '/app/health-score'
    | '/app/improve-value'
    | '/app/onboarding'
    | '/app/recommendations'
    | '/app/reports'
    | '/app/roadmap'
    | '/app/scenarios'
    | '/app/settings'
    | '/teaser/$publicId'
    | '/app/'
    | '/advisor/accept/$inviteId'
    | '/advisor/decline/$inviteId'
    | '/api/public/quickbooks/callback'
    | '/api/public/stripe/webhook'
    | '/api/public/xero/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/auth'
    | '/demo'
    | '/methodology'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/terms'
    | '/unsubscribe'
    | '/app/advisors'
    | '/app/buyer-requests'
    | '/app/buyer-teaser'
    | '/app/data-room'
    | '/app/financials'
    | '/app/health-score'
    | '/app/improve-value'
    | '/app/onboarding'
    | '/app/recommendations'
    | '/app/reports'
    | '/app/roadmap'
    | '/app/scenarios'
    | '/app/settings'
    | '/teaser/$publicId'
    | '/app'
    | '/advisor/accept/$inviteId'
    | '/advisor/decline/$inviteId'
    | '/api/public/quickbooks/callback'
    | '/api/public/stripe/webhook'
    | '/api/public/xero/callback'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/app'
    | '/auth'
    | '/demo'
    | '/methodology'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/terms'
    | '/unsubscribe'
    | '/app/advisors'
    | '/app/buyer-requests'
    | '/app/buyer-teaser'
    | '/app/data-room'
    | '/app/financials'
    | '/app/health-score'
    | '/app/improve-value'
    | '/app/onboarding'
    | '/app/recommendations'
    | '/app/reports'
    | '/app/roadmap'
    | '/app/scenarios'
    | '/app/settings'
    | '/teaser/$publicId'
    | '/app/'
    | '/advisor/accept/$inviteId'
    | '/advisor/decline/$inviteId'
    | '/api/public/quickbooks/callback'
    | '/api/public/stripe/webhook'
    | '/api/public/xero/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  MethodologyRoute: typeof MethodologyRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  TeaserPublicIdRoute: typeof TeaserPublicIdRoute
  ApiPublicQuickbooksCallbackRoute: typeof ApiPublicQuickbooksCallbackRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicXeroCallbackRoute: typeof ApiPublicXeroCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/teaser/$publicId': {
      id: '/teaser/$publicId'
      path: '/teaser/$publicId'
      fullPath: '/teaser/$publicId'
      preLoaderRoute: typeof TeaserPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios': {
      id: '/app/scenarios'
      path: '/scenarios'
      fullPath: '/app/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roadmap': {
      id: '/app/roadmap'
      path: '/roadmap'
      fullPath: '/app/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recommendations': {
      id: '/app/recommendations'
      path: '/recommendations'
      fullPath: '/app/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/improve-value': {
      id: '/app/improve-value'
      path: '/improve-value'
      fullPath: '/app/improve-value'
      preLoaderRoute: typeof AppImproveValueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health-score': {
      id: '/app/health-score'
      path: '/health-score'
      fullPath: '/app/health-score'
      preLoaderRoute: typeof AppHealthScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financials': {
      id: '/app/financials'
      path: '/financials'
      fullPath: '/app/financials'
      preLoaderRoute: typeof AppFinancialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data-room': {
      id: '/app/data-room'
      path: '/data-room'
      fullPath: '/app/data-room'
      preLoaderRoute: typeof AppDataRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyer-teaser': {
      id: '/app/buyer-teaser'
      path: '/buyer-teaser'
      fullPath: '/app/buyer-teaser'
      preLoaderRoute: typeof AppBuyerTeaserRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buyer-requests': {
      id: '/app/buyer-requests'
      path: '/buyer-requests'
      fullPath: '/app/buyer-requests'
      preLoaderRoute: typeof AppBuyerRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advisors': {
      id: '/app/advisors'
      path: '/advisors'
      fullPath: '/app/advisors'
      preLoaderRoute: typeof AppAdvisorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/advisor/decline/$inviteId': {
      id: '/advisor/decline/$inviteId'
      path: '/decline/$inviteId'
      fullPath: '/advisor/decline/$inviteId'
      preLoaderRoute: typeof AdvisorDeclineInviteIdRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/advisor/accept/$inviteId': {
      id: '/advisor/accept/$inviteId'
      path: '/accept/$inviteId'
      fullPath: '/advisor/accept/$inviteId'
      preLoaderRoute: typeof AdvisorAcceptInviteIdRouteImport
      parentRoute: typeof AdvisorRoute
    }
    '/api/public/xero/callback': {
      id: '/api/public/xero/callback'
      path: '/api/public/xero/callback'
      fullPath: '/api/public/xero/callback'
      preLoaderRoute: typeof ApiPublicXeroCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quickbooks/callback': {
      id: '/api/public/quickbooks/callback'
      path: '/api/public/quickbooks/callback'
      fullPath: '/api/public/quickbooks/callback'
      preLoaderRoute: typeof ApiPublicQuickbooksCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdvisorRouteChildren {
  AdvisorAcceptInviteIdRoute: typeof AdvisorAcceptInviteIdRoute
  AdvisorDeclineInviteIdRoute: typeof AdvisorDeclineInviteIdRoute
}

const AdvisorRouteChildren: AdvisorRouteChildren = {
  AdvisorAcceptInviteIdRoute: AdvisorAcceptInviteIdRoute,
  AdvisorDeclineInviteIdRoute: AdvisorDeclineInviteIdRoute,
}

const AdvisorRouteWithChildren =
  AdvisorRoute._addFileChildren(AdvisorRouteChildren)

interface AppRouteChildren {
  AppAdvisorsRoute: typeof AppAdvisorsRoute
  AppBuyerRequestsRoute: typeof AppBuyerRequestsRoute
  AppBuyerTeaserRoute: typeof AppBuyerTeaserRoute
  AppDataRoomRoute: typeof AppDataRoomRoute
  AppFinancialsRoute: typeof AppFinancialsRoute
  AppHealthScoreRoute: typeof AppHealthScoreRoute
  AppImproveValueRoute: typeof AppImproveValueRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppScenariosRoute: typeof AppScenariosRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisorsRoute: AppAdvisorsRoute,
  AppBuyerRequestsRoute: AppBuyerRequestsRoute,
  AppBuyerTeaserRoute: AppBuyerTeaserRoute,
  AppDataRoomRoute: AppDataRoomRoute,
  AppFinancialsRoute: AppFinancialsRoute,
  AppHealthScoreRoute: AppHealthScoreRoute,
  AppImproveValueRoute: AppImproveValueRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppScenariosRoute: AppScenariosRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  MethodologyRoute: MethodologyRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  TeaserPublicIdRoute: TeaserPublicIdRoute,
  ApiPublicQuickbooksCallbackRoute: ApiPublicQuickbooksCallbackRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicXeroCallbackRoute: ApiPublicXeroCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
