ALTER TABLE public.financial_years
  ADD COLUMN IF NOT EXISTS depreciation NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amortization NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS interest NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS income_taxes NUMERIC DEFAULT 0;